import os

WEBFLOW_BOOKINGS_COLLECTION = os.getenv("WEBFLOW_BOOKINGS_COLLECTION")
WEBFLOW_LANDLORDS_COLLECTION = os.getenv("WEBFLOW_LANDLORDS_COLLECTION")
WEBFLOW_PROPERTIES_COLLECTION = os.getenv("WEBFLOW_PROPERTIES_COLLECTION")